#!/usr/bin/env python3
"""
WireGuard VPN Client Manager
This script helps set up and manage WireGuard VPN connections using configurations
generated by the Ephemeral VPN API.
"""

import os
import sys
import json
import subprocess
import requests
from pathlib import Path


class WireGuardClient:
    """WireGuard VPN client manager"""

    def __init__(self, api_base_url: str, master_api_key: str):
        self.api_base_url = api_base_url.rstrip('/')
        self.master_api_key = master_api_key
        self.config_dir = Path.home() / ".ephem-vpn"
        self.config_dir.mkdir(exist_ok=True)

    def create_user(self, client_id: str) -> dict:
        """Create a new WireGuard user via the API"""
        url = f"{self.api_base_url}/users"
        headers = {
            "Authorization": f"Bearer {self.master_api_key}",
            "Content-Type": "application/json"
        }
        data = {"client_id": client_id}

        response = requests.post(url, headers=headers, json=data)

        if response.status_code == 200:
            return response.json()
        else:
            raise Exception(f"Failed to create user: {response.text}")

    def get_user_config(self, client_id: str) -> dict:
        """Get WireGuard configuration for a user"""
        url = f"{self.api_base_url}/users/{client_id}"
        headers = {
            "Authorization": f"Bearer {self.master_api_key}"
        }

        response = requests.get(url, headers=headers)

        if response.status_code == 200:
            return response.json()
        else:
            raise Exception(f"Failed to get user config: {response.text}")

    def save_config(self, client_id: str, config_data: dict):
        """Save WireGuard configuration to file"""
        config_file = self.config_dir / f"{client_id}.conf"

        with open(config_file, 'w') as f:
            f.write(config_data['client_config'])

        print(f"Configuration saved to: {config_file}")
        return config_file

    def connect(self, client_id: str):
        """Connect using WireGuard"""
        config_file = self.config_dir / f"{client_id}.conf"

        if not config_file.exists():
            raise Exception(f"Configuration file not found: {config_file}")

        print(f"Connecting to VPN using {config_file}...")

        try:
            # Bring up the WireGuard interface
            result = subprocess.run(
                ["wg-quick", "up", str(config_file)],
                capture_output=True,
                text=True,
                check=True
            )

            print("✓ VPN connected successfully!")
            print("Run 'curl https://httpbin.org/ip' to verify your IP has changed")

        except subprocess.CalledProcessError as e:
            print(f"✗ Failed to connect: {e.stderr}")
            raise

    def disconnect(self, client_id: str):
        """Disconnect from WireGuard"""
        config_file = self.config_dir / f"{client_id}.conf"

        if not config_file.exists():
            print(f"Configuration file not found: {config_file}")
            return

        print(f"Disconnecting from VPN...")

        try:
            result = subprocess.run(
                ["wg-quick", "down", str(config_file)],
                capture_output=True,
                text=True,
                check=True
            )

            print("✓ VPN disconnected successfully!")

        except subprocess.CalledProcessError as e:
            print(f"✗ Failed to disconnect: {e.stderr}")

    def status(self, client_id: str):
        """Show WireGuard interface status"""
        try:
            result = subprocess.run(
                ["wg", "show"],
                capture_output=True,
                text=True,
                check=True
            )

            print("WireGuard Status:")
            print(result.stdout)

        except subprocess.CalledProcessError as e:
            print(f"No active WireGuard interfaces: {e.stderr}")

    def list_configs(self):
        """List saved configuration files"""
        configs = list(self.config_dir.glob("*.conf"))

        if not configs:
            print("No saved configurations found.")
            return

        print("Saved VPN configurations:")
        for config in configs:
            client_id = config.stem
            print(f"  - {client_id} ({config})")


def check_wireguard_installed():
    """Check if WireGuard tools are installed"""
    try:
        subprocess.run(["wg", "--version"],
                      capture_output=True, check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def main():
    """Main function"""
    if len(sys.argv) < 2:
        print("WireGuard VPN Client Manager")
        print("============================")
        print()
        print("Usage:")
        print("  python wg-client.py setup <api-url> <master-key>")
        print("  python wg-client.py create <client-id>")
        print("  python wg-client.py pull <client-id>")
        print("  python wg-client.py connect <client-id>")
        print("  python wg-client.py disconnect <client-id>")
        print("  python wg-client.py status")
        print("  python wg-client.py list")
        print()
        print("Examples:")
        print("  python wg-client.py setup https://my-vpn.example.com:8000 my-master-key")
        print("  python wg-client.py create alice")
        print("  python wg-client.py pull alice")
        print("  python wg-client.py connect alice")
        print()
        print("Note: Requires WireGuard tools to be installed.")
        sys.exit(1)

    command = sys.argv[1]

    # Check if WireGuard is installed
    if not check_wireguard_installed():
        print("ERROR: WireGuard tools not found.")
        print("Please install WireGuard:")
        print("  Ubuntu/Debian: sudo apt install wireguard wireguard-tools")
        print("  CentOS/RHEL: sudo yum install wireguard-tools")
        print("  macOS: brew install wireguard-tools")
        sys.exit(1)

    if command == "setup":
        if len(sys.argv) < 4:
            print("Usage: python wg-client.py setup <api-url> <master-key>")
            sys.exit(1)

        api_url = sys.argv[2]
        master_key = sys.argv[3]

        # Save setup configuration
        config_dir = Path.home() / ".ephem-vpn"
        config_dir.mkdir(exist_ok=True)

        setup_file = config_dir / "setup.json"
        with open(setup_file, 'w') as f:
            json.dump({
                "api_url": api_url,
                "master_key": master_key
            }, f, indent=2)

        print(f"✓ Setup saved to {setup_file}")

    else:
        # Load setup configuration
        setup_file = Path.home() / ".ephem-vpn" / "setup.json"

        if not setup_file.exists():
            print("ERROR: Not set up yet. Run: python wg-client.py setup <api-url> <master-key>")
            sys.exit(1)

        with open(setup_file) as f:
            setup = json.load(f)

        client = WireGuardClient(setup["api_url"], setup["master_key"])

        if command == "create":
            if len(sys.argv) < 3:
                print("Usage: python wg-client.py create <client-id>")
                sys.exit(1)

            client_id = sys.argv[2]

            try:
                config_data = client.create_user(client_id)
                config_file = client.save_config(client_id, config_data)
                print(f"✓ User '{client_id}' created and configuration saved!")
                print(f"Configuration file: {config_file}")

            except Exception as e:
                print(f"✗ Failed to create user: {e}")

        elif command == "pull":
            if len(sys.argv) < 3:
                print("Usage: python wg-client.py pull <client-id>")
                sys.exit(1)

            client_id = sys.argv[2]

            try:
                config_data = client.get_user_config(client_id)
                config_file = client.save_config(client_id, config_data)
                print(f"✓ Configuration for '{client_id}' retrieved and saved!")
                print(f"Configuration file: {config_file}")

            except Exception as e:
                print(f"✗ Failed to pull user config: {e}")

        elif command == "connect":
            if len(sys.argv) < 3:
                print("Usage: python wg-client.py connect <client-id>")
                sys.exit(1)

            client_id = sys.argv[2]

            try:
                client.connect(client_id)
            except Exception as e:
                print(f"✗ Failed to connect: {e}")

        elif command == "disconnect":
            if len(sys.argv) < 3:
                print("Usage: python wg-client.py disconnect <client-id>")
                sys.exit(1)

            client_id = sys.argv[2]
            client.disconnect(client_id)

        elif command == "status":
            if len(sys.argv) > 2:
                client_id = sys.argv[2]
                client.status(client_id)
            else:
                client.status(None)

        elif command == "list":
            client.list_configs()

        else:
            print(f"Unknown command: {command}")
            sys.exit(1)


if __name__ == "__main__":
    main()
